### ISSUE TITLE
Error of when running ./finetune_t5_large_alone.sh

### ISSUE THREAD

**Issue by jmlongriver** [EagleW/Stage-wise-Fine-tuning#6]
Here is the error:
We have added 3 tokens
Traceback (most recent call last):
  File "/work/c272987/NLG/Stage-wise-Fine-tuning-bak/env/lib/python3.8/site-packages/transformers/modeling_utils.py", line 928, in from_pretrained
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "finetune_t5.py", line 544, in <module>
    main(args)
  File "finetune_t5.py", line 466, in main
    model: SummarizationModule = RDF2textModule(args)
  File "finetune_t5.py", line 398, in __init__
    super().__init__(hparams, **kwargs)
  File "finetune_t5.py", line 383, in __init__
    super().__init__(hparams, **kwargs)
  File "finetune_t5.py", line 67, in __init__
    super().__init__(hparams, num_labels=None, mode=self.mode, **kwargs)
  File "/work/c272987/NLG/Stage-wise-Fine-tuning-bak/src/lightning_base_t5.py", line 129, in __init__
    self.model = self.model_type.from_pretrained(
  File "/work/c272987/NLG/Stage-wise-Fine-tuning-bak/env/lib/python3.8/site-packages/transformers/modeling_utils.py", line 935, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load weights for 't5-large'. Make sure that:

- 't5-large' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-large' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.

**Comment by EagleW** [comment]
What is your environment?

**Comment by EagleW** [comment]
I also think you haven't correctly connected to the Internet, because T5-large is a huggingface model https://huggingface.co/t5-large
